#!/bin/bash

var="8dm7KsjU28B7v621Jls"
value="ERmFRMVZ0U2paTlJYTkxDZz09Cg"
testvar=""
for i in {1..40}
do
        var=$(echo $var | base64)
       testvar=$(echo $var | wc -c)
	if [[ "$var" == "$value" && "$testvar" -gt 113450 ]]
	then	
	echo $var | tall -c 20
	fi
done
