#!/bin/bash

while getopts "n:f:v:" param
do
  case "$param" in
    f) file="$OPTARG" ;;
    n) set -x ;;
    v) set -v;;
    *) echo "Invalid option"
  esac
done

case "$file" in
  *.tar.gz) tar xzf "$file" ;;
#  *.zip) unzip "$file" ;;
  *.gz) gzip -d "$file" ;;
  *) echo "Unknown filetype" ;;
esac

if [ "$(uname)" == "Linux" ]
then
  echo "Using Linux"
fi
